# Generated by Django 3.1.5 on 2021-08-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycrud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='contact',
            field=models.CharField(max_length=32),
        ),
    ]
